### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by tinatsina** [tinatsina/space-travelers-hub-online#26]
## Summary
- Group project for `SpaceX Hub Travellers `webpage
- Initial review issue
- includes all issues made for the project

## Project Link 🔗 
- [KanBan Project Board Here](https://github.com/tinatsina/space-travelers-hub-online/projects/1)

## Collaborators 🧑‍🤝‍🧑 
- @tinatsina 
- @TracyMuso

**Comment by brytebee** [comment]
Hi, @tinatsina & @TracyMuso👋,

##

### Highlights💡
- The team size is given.✔️ 
- There is a link to the Kanban board.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️

- Kindly assign each card to a member of the team.
![image](https://user-images.githubusercontent.com/27709832/193523970-f9389d08-5425-49d1-866a-23d771c5f51f.png)
- Ensure the assignment is fairly done.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tinatsina** [comment]
## Resolved 👍 
- used your advice and made the `assignees` in every issue
- all `18 `issues have assignees
- thanks for noticing 🤝

**Comment by Bondok6** [comment]
# STATUS: APPROVED :green_circle: :clap: 

## Hi Team 🙋‍♂️, 
Your kanbanboard is setup correctly!  There is nothing else to say other than... Great job 👏 

HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

Cheers and Happy coding!👏👏👏
